// MYbloXX
// 0.081420 by MYXXdev
// 
// Powered by MYXX FM
// #1 for Spanglish Hits!
// A DJ MikeyB Station
// MYXXfm.com | MYXX-DB | Dallas, TX

function FindProxyForhost(url, host)

{
    if (
    shExpMatch(host, "*ads*.*") ||
    shExpMatch(host, "*-advertising*") ||
    shExpMatch(host, "*.2o7.net") ||
    shExpMatch(host, "*.am15.net") ||
    shExpMatch(host, "*.bbelements.*") ||
    shExpMatch(host, "*.deltadna.net*") ||
    shExpMatch(host, "*.fractionalmedia.*") ||
    shExpMatch(host, "*.impact-ad*") ||
    shExpMatch(host, "*.marketo.*") ||
    shExpMatch(host, "*.media.net*") ||
    shExpMatch(host, "*.mydas.mobi*") ||
    shExpMatch(host, "*.sextracker*") ||
    shExpMatch(host, "*.stats.esomniture.com*") ||
    shExpMatch(host, "*.undertone*") ||
    shExpMatch(host, "*.voodoo*.*") ||
    shExpMatch(host, "*.xiti.com*") ||
    shExpMatch(host, "*ad-*") ||
    shExpMatch(host, "*ad.*") ||
    shExpMatch(host, "*ad0*-*") ||
    shExpMatch(host, "*ad0*.*") ||
    shExpMatch(host, "*ad1*-*") ||
    shExpMatch(host, "*ad1*.*") ||
    shExpMatch(host, "*ad2*-*") ||
    shExpMatch(host, "*ad2*.*") ||
    shExpMatch(host, "*ad3*-*") ||
    shExpMatch(host, "*ad3*.*") ||
    shExpMatch(host, "*ad4*-*") ||
    shExpMatch(host, "*ad4*.*") ||
    shExpMatch(host, "*ad5*-*") ||
    shExpMatch(host, "*ad5*.*") ||
    shExpMatch(host, "*ad6*-*") ||
    shExpMatch(host, "*ad6*.*") ||
    shExpMatch(host, "*ad7*-*") ||
    shExpMatch(host, "*ad7*.*") ||
    shExpMatch(host, "*ad8*-*") ||
    shExpMatch(host, "*ad8*.*") ||
    shExpMatch(host, "*ad9*-*") ||
    shExpMatch(host, "*ad9*.*") ||
    shExpMatch(host, "*adbanner*-*") ||
    shExpMatch(host, "*adbanner*.*") ||
    shExpMatch(host, "*adblade*") ||
    shExpMatch(host, "*adcolony*") ||
    shExpMatch(host, "*adimag*-*") ||
    shExpMatch(host, "*adimag*.*") ||
    shExpMatch(host, "*adimg*-*") ||
    shExpMatch(host, "*adimg*.*") ||
    shExpMatch(host, "*adlog*-*") ||
    shExpMatch(host, "*adlog*.*") ||
    shExpMatch(host, "*adlogs*-*") ||
    shExpMatch(host, "*adlogs*.*") ||
    shExpMatch(host, "*adlooxtracking*") ||
    shExpMatch(host, "*admob*-*") ||
    shExpMatch(host, "*admob*.*") ||
    shExpMatch(host, "*adnet*-*") ||
    shExpMatch(host, "*adnet*.*") ||
    shExpMatch(host, "*adnetwork*-*") ||
    shExpMatch(host, "*adnetwork*.*") ||
    shExpMatch(host, "*adpushup*") ||
    shExpMatch(host, "*ads*-*") ||
    shExpMatch(host, "*ads-*") ||
    shExpMatch(host, "*ads.*") ||
    shExpMatch(host, "*ads0*-*") ||
    shExpMatch(host, "*ads0*.*") ||
    shExpMatch(host, "*ads1*-*") ||
    shExpMatch(host, "*ads1*.*") ||
    shExpMatch(host, "*ads2*-*") ||
    shExpMatch(host, "*ads2*.*") ||
    shExpMatch(host, "*ads3*-*") ||
    shExpMatch(host, "*ads3*.*") ||
    shExpMatch(host, "*ads4*-*") ||
    shExpMatch(host, "*ads4*.*") ||
    shExpMatch(host, "*ads5*-*") ||
    shExpMatch(host, "*ads5*.*") ||
    shExpMatch(host, "*ads6*-*") ||
    shExpMatch(host, "*ads6*.*") ||
    shExpMatch(host, "*ads7*-*") ||
    shExpMatch(host, "*ads7*.*") ||
    shExpMatch(host, "*ads8*-*") ||
    shExpMatch(host, "*ads8*.*") ||
    shExpMatch(host, "*ads9*-*") ||
    shExpMatch(host, "*ads9*.*") ||
    shExpMatch(host, "*adsapi*-*") ||
    shExpMatch(host, "*adsapi*.*") ||
    shExpMatch(host, "*adscience*.*") ||
    shExpMatch(host, "*adsdk*-*") ||
    shExpMatch(host, "*adsdk*.*") ||
    shExpMatch(host, "*adserv*-*") ||
    shExpMatch(host, "*adserv*.*") ||
    shExpMatch(host, "*adservice*-*") ||
    shExpMatch(host, "*adservice*.*") ||
    shExpMatch(host, "*adserving*-*") ||
    shExpMatch(host, "*adserving*.*") ||
    shExpMatch(host, "*adsrv*-*") ||
    shExpMatch(host, "*adsrv*.*") ||
    shExpMatch(host, "*adtech*") ||
    shExpMatch(host, "*adtrack*-*") ||
    shExpMatch(host, "*adtrack*.*") ||
    shExpMatch(host, "*advert*-*") ||
    shExpMatch(host, "*advert*.*") ||
    shExpMatch(host, "*affiliate*-*") ||
    shExpMatch(host, "*affiliate*.*") ||
    shExpMatch(host, "*analytic*-*") ||
    shExpMatch(host, "*analytic*.*") ||
    shExpMatch(host, "*banner*-*") ||
    shExpMatch(host, "*banner*.*") ||
    shExpMatch(host, "*bidvertiser*") ||
    shExpMatch(host, "*buysellads*") ||
    shExpMatch(host, "*cdn*-*") ||
    shExpMatch(host, "*cdn*.*") ||
    shExpMatch(host, "*cdnads*-*") ||
    shExpMatch(host, "*cdnads*.*") ||
    shExpMatch(host, "*clickserv*.*") ||
    shExpMatch(host, "*clickstats*.*") ||
    shExpMatch(host, "*clicktrack*.*") ||
    shExpMatch(host, "*collector*-*") ||
    shExpMatch(host, "*collector*.*") ||
    shExpMatch(host, "*conversant*") ||
    shExpMatch(host, "*count-*") ||
    shExpMatch(host, "*count.*") ||
    shExpMatch(host, "*cpcalendars*-*") ||
    shExpMatch(host, "*cpcalendars*.*") ||
    shExpMatch(host, "*cpcontacts*-*") ||
    shExpMatch(host, "*cpcontacts*.*") ||
    shExpMatch(host, "*cqcounter*") ||
    shExpMatch(host, "*creativecdn*") ||
    shExpMatch(host, "*crittercism*") ||
    shExpMatch(host, "*doubleclick*") ||
    shExpMatch(host, "*doubleverify*") ||
    shExpMatch(host, "*exacttarget*") ||
    shExpMatch(host, "*fastclick*") ||
    shExpMatch(host, "*googleads*") ||
    shExpMatch(host, "*googleadservices*") ||
    shExpMatch(host, "*googlesyndication*") ||
    shExpMatch(host, "*hitbox*") ||
    shExpMatch(host, "*iad*-*") ||
    shExpMatch(host, "*iad*.*") ||
    shExpMatch(host, "*infolinks*") ||
    shExpMatch(host, "*intellitxt*") ||
    shExpMatch(host, "*iwanttodeliver*") ||
    shExpMatch(host, "*lijit*-*") ||
    shExpMatch(host, "*logger*-*") ||
    shExpMatch(host, "*logger*.*") ||
    shExpMatch(host, "*logging*-*") ||
    shExpMatch(host, "*logging*.*") ||
    shExpMatch(host, "*logs*-*") ||
    shExpMatch(host, "*logs*.*") ||
    shExpMatch(host, "*marketing*-*") ||
    shExpMatch(host, "*marketing*.*") ||
    shExpMatch(host, "*metrics*-*") ||
    shExpMatch(host, "*metrics*.*") ||
    shExpMatch(host, "*mobileads*") ||
    shExpMatch(host, "*mobileapptracking*") ||
    shExpMatch(host, "*ocsp-*") ||
    shExpMatch(host, "*ocsp.*") ||
    shExpMatch(host, "*offers*-*") ||
    shExpMatch(host, "*offers*.*") ||
    shExpMatch(host, "*pagead*-*") ||
    shExpMatch(host, "*pagead*.*") ||
    shExpMatch(host, "*partner*-*") ||
    shExpMatch(host, "*partner*.*") ||
    shExpMatch(host, "*popunder*-*") ||
    shExpMatch(host, "*popunder*.*") ||
    shExpMatch(host, "*popup*-*") ||
    shExpMatch(host, "*popup*.*") ||
    shExpMatch(host, "*promo*-*") ||
    shExpMatch(host, "*promo*.*") ||
    shExpMatch(host, "*redir*-*") ||
    shExpMatch(host, "*redir*.*") ||
    shExpMatch(host, "*smartyads*") ||
    shExpMatch(host, "*splicky*") ||
    shExpMatch(host, "*spylog*") ||
    shExpMatch(host, "*statcounter*") ||
    shExpMatch(host, "*statistic*-*") ||
    shExpMatch(host, "*statistic*.*") ||
    shExpMatch(host, "*stats*-*") ||
    shExpMatch(host, "*stats*.*") ||
    shExpMatch(host, "*swrve*") ||
    shExpMatch(host, "*taboola*") ||
    shExpMatch(host, "*textad*-*") ||
    shExpMatch(host, "*textad*.*") ||
    shExpMatch(host, "*track*-*") ||
    shExpMatch(host, "*track*.*") ||
    shExpMatch(host, "*tradedoubler*") ||
    shExpMatch(host, "*trk*-*") ||
    shExpMatch(host, "*trk*.*") ||
    shExpMatch(host, "*vibrantmedia*") ||
    shExpMatch(host, "*webads*-*") ||
    shExpMatch(host, "*webads*.*") ||
    shExpMatch(host, "*yads*-*") ||
    shExpMatch(host, "*yads*.*") ||
    shExpMatch(host, "*zeroredirect*")
    )
    {return "PROXY 8.8.8.8:53";}

return "DIRECT";

}