//
// Last Updated: 08/16/20 - 03:36 CST
// 
// ┏━┓┏━┳┓╋╋┏┳┓╋┏┓╋╋╋┏━┓┏━┳━┓┏━┓
// ┃┃┗┛┃┃┗┓┏┛┃┃╋┃┃╋╋╋┗┓┗┛┏┻┓┗┛┏┛
// ┃┏┓┏┓┣┓┗┛┏┫┗━┫┃┏━━┓┗┓┏┛╋┗┓┏┛
// ┃┃┃┃┃┃┗┓┏┛┃┏┓┃┃┃┏┓┃┏┛┗┓╋┏┛┗┓
// ┃┃┃┃┃┃╋┃┃╋┃┗┛┃┗┫┗┛┣┛┏┓┗┳┛┏┓┗┓
// ┗┛┗┛┗┛╋┗┛╋┗━━┻━┻━━┻━┛┗━┻━┛┗━┛
// for iOS + 0.081620 by MYXXdev
// 
// Powered by MYXX FM
// #1 for Spanglish Hits!
// A DJ MikeyB Station
// MYXXfm.com | MYXX-DB | Dallas, TX

function FindProxyForURL(url, host)

{
    if (
    shExpMatch(url, "*1phads*") ||
    shExpMatch(url, "*2mdn*") ||
    shExpMatch(url, "*-ads*") ||
    shExpMatch(url, "*-advert*") ||
    shExpMatch(url, "*.2o7.net") ||
    shExpMatch(url, "*.am15.net") ||
    shExpMatch(url, "*.impact-ad*") ||
    shExpMatch(url, "*.marketo.*") ||
    shExpMatch(url, "*.media.net*") ||
    shExpMatch(url, "*.top") ||
    shExpMatch(url, "*.undertone*") ||
    shExpMatch(url, "*/ad_*") ||
    shExpMatch(url, "*/adcount*") ||
    shExpMatch(url, "*/ads/*") ||
    shExpMatch(url, "*/advertising.js*") ||
    shExpMatch(url, "*/click/*") ||
    shExpMatch(url, "*/eas?c*") ||
    shExpMatch(url, "*_campaign*") ||
    shExpMatch(url, "*aclk*") ||
    shExpMatch(url, "*acloudimages*") ||
    shExpMatch(url, "*acloudvideos*") ||
    shExpMatch(url, "*ad*-*") ||
    shExpMatch(url, "*ad*.*") ||
    shExpMatch(url, "*adap.tv*") ||
    shExpMatch(url, "*adbanner*") ||
    shExpMatch(url, "*adblade*") ||
    shExpMatch(url, "*adbureau*") ||
    shExpMatch(url, "*adchoices*") ||
    shExpMatch(url, "*adcolony*") ||
    shExpMatch(url, "*adcouncil*") ||
    shExpMatch(url, "*adexprt*") ||
    shExpMatch(url, "*adfeedback*") ||
    shExpMatch(url, "*adimag*") ||
    shExpMatch(url, "*adimg*") ||
    shExpMatch(url, "*adk2*") ||
    shExpMatch(url, "*adlog*") ||
    shExpMatch(url, "*adlooxtracking*") ||
    shExpMatch(url, "*admedit*") ||
    shExpMatch(url, "*admitad*") ||
    shExpMatch(url, "*admob*") ||
    shExpMatch(url, "*adnet*") ||
    shExpMatch(url, "*adnetwork*") ||
    shExpMatch(url, "*adnxs*") ||
    shExpMatch(url, "*adpushup*") ||
    shExpMatch(url, "*ads*-*") ||
    shExpMatch(url, "*ads*.*") ||
    shExpMatch(url, "*adroll*") ||
    shExpMatch(url, "*adsapi*") ||
    shExpMatch(url, "*adsatt*") ||
    shExpMatch(url, "*adscience*.*") ||
    shExpMatch(url, "*adsdk*") ||
    shExpMatch(url, "*adsense*") ||
    shExpMatch(url, "*adserv*") ||
    shExpMatch(url, "*AdServer*") ||
    shExpMatch(url, "*adsmogo*") ||
    shExpMatch(url, "*adsperk*") ||
    shExpMatch(url, "*adsrv*") ||
    shExpMatch(url, "*adstreamcanvas*") ||
    shExpMatch(url, "*adtech*") ||
    shExpMatch(url, "*adtechus*") ||
    shExpMatch(url, "*adtng*") ||
    shExpMatch(url, "*adtrack*") ||
    shExpMatch(url, "*advert*") ||
    shExpMatch(url, "*affiliate*") ||
    shExpMatch(url, "*aimatch*") ||
    shExpMatch(url, "*altrooz*") ||
    shExpMatch(url, "*amobee*") ||
    shExpMatch(url, "*analytic*") ||
    shExpMatch(url, "*anamuel-careslie*") ||
    shExpMatch(url, "*andomedia*") ||
    shExpMatch(url, "*api.zynga.com*") ||
    shExpMatch(url, "*appads*") ||
    shExpMatch(url, "*appflood*") ||
    shExpMatch(url, "*applovin*") ||
    shExpMatch(url, "*appmessages.com*") ||
    shExpMatch(url, "*apprupt*") ||
    shExpMatch(url, "*atdmt*") ||
    shExpMatch(url, "*atlant-track*") ||
    shExpMatch(url, "*atwola*") ||
    shExpMatch(url, "*banner*") ||
    shExpMatch(url, "*bbelements*") ||
    shExpMatch(url, "*bcfads*") ||
    shExpMatch(url, "*beonixom*") ||
    shExpMatch(url, "*betgorebysson*") ||
    shExpMatch(url, "*bidvertis*") ||
    shExpMatch(url, "*bnmla*") ||
    shExpMatch(url, "*brightroll*") ||
    shExpMatch(url, "*btrll*") ||
    shExpMatch(url, "*buysellads*") ||
    shExpMatch(url, "*cdnads*") ||
    shExpMatch(url, "*chartboost*") ||
    shExpMatch(url, "*clickserv*") ||
    shExpMatch(url, "*clickstat*") ||
    shExpMatch(url, "*clicktr*") ||
    shExpMatch(url, "*clksite*") ||
    shExpMatch(url, "*cloudfront.net*") ||
    shExpMatch(url, "*collector*") ||
    shExpMatch(url, "*conversant*") ||
    shExpMatch(url, "*cpcalendars*") ||
    shExpMatch(url, "*cpcontacts*") ||
    shExpMatch(url, "*cqcounter*") ||
    shExpMatch(url, "*creativecdn*") ||
    shExpMatch(url, "*crittercism*") ||
    shExpMatch(url, "*dealtime*") ||
    shExpMatch(url, "*deltadna*") ||
    shExpMatch(url, "*doubleclick*") ||
    shExpMatch(url, "*doubleverify*") ||
    shExpMatch(url, "*ebaycommercenetwork*") ||
    shExpMatch(url, "*eikegolehem*") ||
    shExpMatch(url, "*emediate*") ||
    shExpMatch(url, "*esomniture*") ||
    shExpMatch(url, "*exacttarget*") ||
    shExpMatch(url, "*exoclick*") ||
    shExpMatch(url, "*exosrv*") ||
    shExpMatch(url, "*exponential*") ||
    shExpMatch(url, "*eyewonder*") ||
    shExpMatch(url, "*familinger*") ||
    shExpMatch(url, "*fastclick*") ||
    shExpMatch(url, "*fcukfriend*") ||
    shExpMatch(url, "*fingerarts*") ||
    shExpMatch(url, "*fluentmobile*") ||
    shExpMatch(url, "*flurry.com*") ||
    shExpMatch(url, "*fractionalmedia*") ||
    shExpMatch(url, "*fstsrv*") ||
    shExpMatch(url, "*fusepowered*") ||
    shExpMatch(url, "*fwmrm*") ||
    shExpMatch(url, "*getAd*") ||
    shExpMatch(url, "*getads*") ||
    shExpMatch(url, "*getadmiral*") ||
    shExpMatch(url, "*qfjherc*") ||
    shExpMatch(url, "*globaltraffico*") ||
    shExpMatch(url, "*goaffmy*") ||
    shExpMatch(url, "*googleads*") ||
    shExpMatch(url, "*googlesyndication*") ||
    shExpMatch(url, "*googletagmanager*") ||        
    shExpMatch(url, "*googletagservices*") ||
    shExpMatch(url, "*graizoah*") ||
    shExpMatch(url, "*graph.facebook.com*") ||
    shExpMatch(url, "*greystripe.com*") ||
    shExpMatch(url, "*grooksom*") ||
    shExpMatch(url, "*hastrk2*") ||
    shExpMatch(url, "*hitbox*") ||
    shExpMatch(url, "*hotwords.com*") ||
    shExpMatch(url, "*hpyrdr*") ||
    shExpMatch(url, "*hsh51nvkrv*") ||
    shExpMatch(url, "*iadnet*") ||
    shExpMatch(url, "*icemochi*") ||
    shExpMatch(url, "*iclickcdn*") ||        
    shExpMatch(url, "*infolinks*") ||
    shExpMatch(url, "*infopicked*") ||
    shExpMatch(url, "*inmobi*") ||
    shExpMatch(url, "*innovid*") ||
    shExpMatch(url, "*inpagepush*") ||
    shExpMatch(url, "*intellitxt*") ||
    shExpMatch(url, "*interad*") ||
    shExpMatch(url, "*interstitial*") ||
    shExpMatch(url, "*itunesredir*") ||
    shExpMatch(url, "*iwanttodeliver*") ||
    shExpMatch(url, "*jumptap*") ||
    shExpMatch(url, "*lalaping*") ||
    shExpMatch(url, "*lijit*") ||
    shExpMatch(url, "*liverail*") ||
    shExpMatch(url, "*logger*") ||
    shExpMatch(url, "*logging*") ||
    shExpMatch(url, "*m2pub*") ||
    shExpMatch(url, "*mads*") ||
    shExpMatch(url, "*madsone*") ||
    shExpMatch(url, "*madvertise*") ||
    shExpMatch(url, "*mainspotvideosfree*") ||
    shExpMatch(url, "*mdotm*") ||
    shExpMatch(url, "*mesu.*") ||
    shExpMatch(url, "*medialets*") ||
    shExpMatch(url, "*medialytics*") ||
    shExpMatch(url, "*meowpushnot*") ||
    shExpMatch(url, "*metrics*") ||
    shExpMatch(url, "*mirando*") ||
    shExpMatch(url, "*mobclix*") ||
    shExpMatch(url, "*mobfox*") ||
    shExpMatch(url, "*mobile-creatives*") ||
    shExpMatch(url, "*mobile_interstitials*") ||
    shExpMatch(url, "*mobileads*") ||
    shExpMatch(url, "*mobileapptracking*") ||
    shExpMatch(url, "*mobilefuse*") ||
    shExpMatch(url, "*mobiletheory*") ||
    shExpMatch(url, "*mocean*") ||
    shExpMatch(url, "*mol11*") ||        
    shExpMatch(url, "*mopinion*") ||
    shExpMatch(url, "*mopub*") ||
    shExpMatch(url, "*mrjb7hvcks*") ||
    shExpMatch(url, "*mycdn*") ||
    shExpMatch(url, "*mydas*") ||
    shExpMatch(url, "*netshelter*") ||
    shExpMatch(url, "*newsandpromotions*") ||
    shExpMatch(url, "*ocsp*") ||
    shExpMatch(url, "*offerimage*") ||
    shExpMatch(url, "*onelink.me*") ||
    shExpMatch(url, "*onstunkyr*") ||
    shExpMatch(url, "*openvideoads*") ||
    shExpMatch(url, "*outbrain*") ||
    shExpMatch(url, "*pagead*") ||
    shExpMatch(url, "*pflexads*") ||
    shExpMatch(url, "*placement=*") ||
    shExpMatch(url, "*popadscdn*") ||
    shExpMatch(url, "*popunder*") ||
    shExpMatch(url, "*popup*") ||
    shExpMatch(url, "*postlnk*") ||
    shExpMatch(url, "*propellerads*") ||
    shExpMatch(url, "*propu.sh*") ||
    shExpMatch(url, "*protomob*") ||
    shExpMatch(url, "*pubmatic*") ||
    shExpMatch(url, "*pushails*") ||
    shExpMatch(url, "*quantcount*") ||
    shExpMatch(url, "*rarenok*") ||
    shExpMatch(url, "*readserver*") ||
    shExpMatch(url, "*realsrv*") ||
    shExpMatch(url, "*redir*") ||
    shExpMatch(url, "*revmob*") ||
    shExpMatch(url, "*rnmd*") ||
    shExpMatch(url, "*rsaltsjt*") ||
    shExpMatch(url, "*rtbpop*") ||
    shExpMatch(url, "*rtbsuperhub*") ||
    shExpMatch(url, "*rubiconproject*") ||
    shExpMatch(url, "*runative*") ||
    shExpMatch(url, "*rusenov*") ||
    shExpMatch(url, "*s3.amazonaws.com/fa-production*/*") ||
    shExpMatch(url, "*scorecardresearch*") ||
    shExpMatch(url, "*sextracker*") ||
    shExpMatch(url, "*sillrochester*") ||
    shExpMatch(url, "*slickmodal*") ||
    shExpMatch(url, "*smaato*") ||
    shExpMatch(url, "*smartadserver*") ||
    shExpMatch(url, "*smartclip*") ||
    shExpMatch(url, "*smarturl*") ||
    shExpMatch(url, "*smartyads*") ||
    shExpMatch(url, "*socialbars*") ||
    shExpMatch(url, "*splicky*") ||
    shExpMatch(url, "*sponsored*") ||
    shExpMatch(url, "*spylog*") ||
    shExpMatch(url, "*statcounter*") ||
    shExpMatch(url, "*static-moreinfo*") ||
    shExpMatch(url, "*stats*") ||
    shExpMatch(url, "*swrve*") ||
    shExpMatch(url, "*synergy*") ||
    shExpMatch(url, "*taboola*") ||
    shExpMatch(url, "*tapjoy*") ||
    shExpMatch(url, "*textad*") ||
    shExpMatch(url, "*tradedoubler*") ||
    shExpMatch(url, "*traffichaus*") ||
    shExpMatch(url, "*trafficjunky*") ||
    shExpMatch(url, "*trafficstars*") ||
    shExpMatch(url, "*transpera*") ||
    shExpMatch(url, "*tribalfusion*") ||
    shExpMatch(url, "*tsyndicate*") ||
    shExpMatch(url, "*u002D*") ||
    shExpMatch(url, "*uimserv*") ||
    shExpMatch(url, "*ulukaris*") ||
    shExpMatch(url, "*umeng*") ||
    shExpMatch(url, "*upgulpinon*") ||
    shExpMatch(url, "*ushoofop*") ||
    shExpMatch(url, "*vibrantmedia*") ||
    shExpMatch(url, "*voodoo*") ||
    shExpMatch(url, "*vpnadefenseplus*") ||
    shExpMatch(url, "*vserv.mobi*") ||
    shExpMatch(url, "*wct.link*") ||
    shExpMatch(url, "*webads*") ||
    shExpMatch(url, "*webgains*") ||
    shExpMatch(url, "*wigetmedia*") ||
    shExpMatch(url, "*xiti.com*") ||
    shExpMatch(url, "*xuossk3tu6hb*") ||
    shExpMatch(url, "*yads*") ||
    shExpMatch(url, "*yahoo*ads*") ||
    shExpMatch(url, "*yieldmanager*") ||
    shExpMatch(url, "*yieldmo*") ||
    shExpMatch(url, "*yoc.mobi*") ||
    shExpMatch(url, "*ythome*") ||
    shExpMatch(url, "*yumenetworks*") ||
    shExpMatch(url, "*zedo.com*") ||
    shExpMatch(url, "*zeroredirect*") ||
    shExpMatch(url, "*zestadz*") ||
    shExpMatch(url, "*zumobi*") ||
    shExpMatch(url, "http*://ad*-*") ||
    shExpMatch(url, "http*://ad*.*") ||
    shExpMatch(url, "http*://ads*-*") ||
    shExpMatch(url, "http*://ads*.*") ||
    shExpMatch(url, "http*://count*-*") ||
    shExpMatch(url, "http*://count*.*") ||
    shExpMatch(url, "http*://counter*-*") ||
    shExpMatch(url, "http*://counter*.*") ||
    shExpMatch(url, "http*://iad*.*") ||
    shExpMatch(url, "http*://iads*.*") ||
    shExpMatch(url, "http*://logs*-*") ||
    shExpMatch(url, "http*://logs*.*") ||
    shExpMatch(url, "http*://marketing*-*") ||
    shExpMatch(url, "http*://marketing*.*") ||
    shExpMatch(url, "http*://offers*-*") ||
    shExpMatch(url, "http*://offers*.*") ||
    shExpMatch(url, "http*://partner*-*") ||
    shExpMatch(url, "http*://partner*.*") ||
    shExpMatch(url, "http*://promo*-*") ||
    shExpMatch(url, "http*://promo*.*") ||
    shExpMatch(url, "http*://stat-*") ||
    shExpMatch(url, "http*://stat.*") ||
    shExpMatch(url, "http*://statistic*-*") ||
    shExpMatch(url, "http*://statistic*.*") ||
    shExpMatch(url, "http*://track*-*") ||
    shExpMatch(url, "http*://track*.*") ||
    shExpMatch(url, "http*://traffic-*") ||
    shExpMatch(url, "http*://traffic.*") ||
    shExpMatch(url, "http*://trk*-*") ||
    shExpMatch(url, "http*://trk*.*")
        )
    {return "PROXY 8.8.8.8:53";}

return "DIRECT";

}